// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1ibu_X-MUxKgltOa8TQPcPZ3gS1hObsU',
    appId: '1:80410007107:web:4e2d6ce145d83b4c5b26f6',
    messagingSenderId: '80410007107',
    projectId: 'am-adel-restaurant',
    authDomain: 'am-adel-restaurant.firebaseapp.com',
    storageBucket: 'am-adel-restaurant.firebasestorage.app',
    measurementId: 'G-MTPLXLB6J8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE1cQKyMh6HARg9CH2OAQQwe0xdxBHr-4',
    appId: '1:80410007107:android:337e6b90b6d503195b26f6',
    messagingSenderId: '80410007107',
    projectId: 'am-adel-restaurant',
    storageBucket: 'am-adel-restaurant.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEpoqphQwj5XHwErfTVAKXRIvUDazFGRg',
    appId: '1:80410007107:ios:14926c7d01698d6f5b26f6',
    messagingSenderId: '80410007107',
    projectId: 'am-adel-restaurant',
    storageBucket: 'am-adel-restaurant.firebasestorage.app',
    iosBundleId: 'com.example.amAdelDashboard',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEpoqphQwj5XHwErfTVAKXRIvUDazFGRg',
    appId: '1:80410007107:ios:14926c7d01698d6f5b26f6',
    messagingSenderId: '80410007107',
    projectId: 'am-adel-restaurant',
    storageBucket: 'am-adel-restaurant.firebasestorage.app',
    iosBundleId: 'com.example.amAdelDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1ibu_X-MUxKgltOa8TQPcPZ3gS1hObsU',
    appId: '1:80410007107:web:709ae1b721e79dd75b26f6',
    messagingSenderId: '80410007107',
    projectId: 'am-adel-restaurant',
    authDomain: 'am-adel-restaurant.firebaseapp.com',
    storageBucket: 'am-adel-restaurant.firebasestorage.app',
    measurementId: 'G-R925PW9Z2W',
  );
}
